"""Stock-aware rest cleanup from previously generated cutter stages.

Rather than running a denser full-area raster under a Rest label, simulate
existing stages on stock then probe the smaller selected cutter at each new
raster tool-centre. Only grid centres whose swept cutter surface would remove
more than the configured residual allowance are kept. All resulting moves are
generated by the existing cutter-contact-safe raster planner, including
retracts across disconnected unmachined regions.

This is sampled 2.5D rest cleanup, not collision/holder verification or
continuous-volume CSG. The existing mandatory fixture/machine preflight
still runs on final G-code output.
"""
from __future__ import annotations

from collections.abc import Callable
from math import isfinite

import numpy as np
import trimesh

from carvefoundry.core.tools import Cutter

from .basic_ops import BasicCamSettings, _finish_settings
from .contact import CutterContactMap
from .finish import calculate_3d_finish
from .raster import _grid_lines, generate_raster_finishing
from .stock_simulation import StockRemovalResult, _tool_sample
from .toolpath import Toolpath

MAX_PROBE_CENTRES = 500_000


def stock_aware_rest_3d(
    mesh: trimesh.Trimesh,
    cutter: Cutter,
    settings: BasicCamSettings,
    previous_stock: StockRemovalResult,
    *,
    minimum_remaining_mm: float = 0.15,
    progress: Callable[[float, str], None] | None = None,
) -> Toolpath:
    """Generate rest cuts using already-simulated stock, not a generic raster.

    The previous stock includes only preceding cutter operations. At each
    contact-safe position, trial-removing material to cutter-tip Z plus
    minimum_remaining_mm determines whether cleanup is useful. A locally
    copied patch ensures every probe is independent: a useful point cannot
    falsely suppress the neighbouring points needed for a smooth finish.
    Unselected tool centres become NaN in the contact map; existing raster
    safety/linking rules handle the disconnected regions.
    """
    if not isfinite(minimum_remaining_mm) or not 0 < minimum_remaining_mm <= 5:
        raise ValueError("Rest allowance must be finite and in (0, 5] mm.")
    if not isfinite(settings.safe_z_mm) or settings.safe_z_mm <= 0:
        raise ValueError("Rest machining requires positive stock-top Safe Z.")
    bounds = np.asarray(mesh.bounds, dtype=float)
    if not np.isfinite(bounds).all():
        raise ValueError("Rest model bounds are invalid.")
    if (
        bounds[0, 0] < -1e-6 or bounds[0, 1] < -1e-6
        or bounds[1, 0] > previous_stock.x_mm[-1] + 1e-6
        or bounds[1, 1] > previous_stock.y_mm[-1] + 1e-6
    ):
        raise ValueError(
            "Rest machining model must be fully inside XY stock. "
            "Correct placement before generating any cutter stages."
        )

    rest_settings = _finish_settings(mesh, cutter, settings, quality="rest")
    if progress is not None:
        progress(0.0, "Sampling target model surface and compensating cutter")
    computed = calculate_3d_finish(
        mesh, cutter, rest_settings, name="3D Rest",
        progress=(
            lambda fraction: progress(
                0.60 * fraction, "Preparing cutter-contact-safe cleanup grid",
            )
            if progress is not None else None
        ),
    )
    contact = computed.contact
    scan_lines = _grid_lines(contact, rest_settings.raster)
    count = sum(len(line) for line in scan_lines)
    if count > MAX_PROBE_CENTRES:
        raise ValueError(
            f"Rest strategy needs {count:,} probe centres; limit is "
            f"{MAX_PROBE_CENTRES:,}. Reduce Detail/increase stepover."
        )

    x = previous_stock.x_mm
    y = previous_stock.y_mm
    previous = previous_stock.remaining_z_mm.astype(float)
    if previous.shape != (len(y), len(x)):
        raise ValueError("Previous stock data has incompatible grid axes.")
    # A probe edits only a local cutter-footprint view, restored after every
    # candidate. A single probe cannot erase a neighbouring opportunity.
    scratch = previous.copy()
    masked = np.full_like(contact.tip_z_mm, np.nan)
    examined = 0
    needed = 0
    radius = cutter.radius_mm
    bottom = float(np.min(previous)) - max(
        0.0, float(mesh.bounds[1, 2] - mesh.bounds[0, 2]),
    )

    for line in scan_lines:
        for yi, xi in line:
            iy, ix = int(yi), int(xi)
            tip = float(contact.tip_z_mm[iy, ix])
            examined += 1
            if np.isfinite(tip):
                center_x = float(contact.surface.x_mm[ix])
                center_y = float(contact.surface.y_mm[iy])
                ix0 = max(0, int(np.searchsorted(x, center_x - radius, side="left")))
                ix1 = min(len(x), int(np.searchsorted(x, center_x + radius, side="right")))
                iy0 = max(0, int(np.searchsorted(y, center_y - radius, side="left")))
                iy1 = min(len(y), int(np.searchsorted(y, center_y + radius, side="right")))
                if ix0 < ix1 and iy0 < iy1:
                    region = scratch[iy0:iy1, ix0:ix1]
                    before = region.copy()
                    changed = _tool_sample(
                        scratch, x, y, cutter,
                        center_x, center_y, tip + minimum_remaining_mm,
                        bottom,
                    )
                    region[:] = before
                    if changed:
                        masked[iy, ix] = tip
                        needed += 1
            if progress is not None and examined % 512 == 0:
                progress(
                    0.60 + 0.30 * examined / max(count, 1),
                    f"Checking stock left by preceding cutters: "
                    f"{examined:,}/{count:,} sample centres",
                )
    if not needed:
        raise ValueError(
            "No stock-aware rest cuts found above the selected allowance. "
            "Existing cutter stages already cleared the sampled target, or "
            "the rest resolution/allowance is too coarse. The prior job is unchanged."
        )

    # Include one neighbour on either side of useful sample centres for
    # smooth approach/departure. Never extend outside the valid target.
    for line in scan_lines:
        if len(line) < 2:
            continue
        yi, xi = line[:, 0], line[:, 1]
        keep = np.isfinite(masked[yi, xi])
        expanded = keep.copy()
        expanded[1:] |= keep[:-1]
        expanded[:-1] |= keep[1:]
        original = contact.tip_z_mm[yi, xi]
        valid = expanded & np.isfinite(original)
        masked[yi[valid], xi[valid]] = original[valid]

    if progress is not None:
        progress(0.92, "Building connected rest cuts and safe retracts")
    rest_contact = CutterContactMap(contact.surface, cutter, masked)
    toolpath = generate_raster_finishing(
        rest_contact, rest_settings.raster, name="3D Stock-Aware Rest",
        progress=(
            lambda fraction: progress(
                0.92 + 0.08 * fraction, "Building safe rest passes",
            )
            if progress is not None else None
        ),
    )
    toolpath.operation = "3d_rest_raster"
    return toolpath
