//! CNC-conscious Rust CAD model. No Python, G-code, or controller dependencies.
//! This crate intentionally has NO machine-export implementation.
pub mod geometry;
pub mod project;
pub mod path;
pub mod editor;
pub mod shapes;
pub mod placement;
pub mod arrange;
pub mod interaction;
pub mod svg;
pub mod dxf;
pub mod text;
pub mod organization;
pub mod topology;
pub mod intersections;
mod bezier_intersections;
pub use editor::{Action, Editor};
pub use shapes::{create_shape, polyline, ShapeKind};
pub use placement::{shape_placement, ShapePlacement};
pub use arrange::{Arrangement,Bounds,vector_bounds,arrangement_offsets};
pub use interaction::{pick, movement_delta, nearest_snap, marquee_ids, SnapTarget, SnapKind, Hit, PickMode};
pub use geometry::{Point, polygon_contains};
pub use svg::{SvgVectors,import_svg,export_svg};
pub use dxf::{DxfVectors,import_dxf,export_dxf};
pub use text::{TextSpec,TextRun,outline_text};
pub use organization::{DesignLayer,LayerMember,VectorGroup};
pub use intersections::{IntersectionHit,IntersectionScan,find_intersections};
pub use project::{Contour, Fixture, Project, Stock, MAX_COORD_MM};
pub use path::{AnalyticPath, Curve, PathNode, PathSegment, Primitive};
